version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: react-mongo
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo: